version: "3"
services:
  jupyter:
    build:
      context: .
    image: ds093
    container_name: ds093
    ports:
      - "11000:8888"
    volumes:
      - ./:/opt/project
      - /mnt/sdb1/data/:/opt/data/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: >
      bash -c "
      cd /opt/project/ && jupyter notebook --no-browser --allow-root --ip='*' --port=8888 --NotebookApp.password='' --NotebookApp.token=''
      "
